# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for phone_farm_cli.py — one-file executable."""

import sys
import os

# The spec is exec'd, not imported — use os.getcwd() as project root
PROJECT_ROOT = os.getcwd()

a = Analysis(
    [os.path.join(PROJECT_ROOT, "phone_farm_cli.py")],
    pathex=[
        PROJECT_ROOT,
        os.path.join(PROJECT_ROOT, "core"),
        os.path.join(PROJECT_ROOT, "scheduler"),
        os.path.join(PROJECT_ROOT, "monitor"),
        os.path.join(PROJECT_ROOT, "ai"),
        os.path.join(PROJECT_ROOT, "config"),
        os.path.join(PROJECT_ROOT, "utils"),
    ],
    binaries=[],
    datas=[
        (os.path.join(PROJECT_ROOT, "config", "phone_farm.yaml"), "config"),
        # ADB binary + Windows DLL dependencies (required for ADB to function)
        (os.path.join(PROJECT_ROOT, "tools", "adb", "adb.exe"), os.path.join("tools", "adb")),
        (os.path.join(PROJECT_ROOT, "tools", "adb", "AdbWinApi.dll"), os.path.join("tools", "adb")),
        (os.path.join(PROJECT_ROOT, "tools", "adb", "AdbWinUsbApi.dll"), os.path.join("tools", "adb")),
    ],
    hiddenimports=[
        "yaml",
        "dotenv",
        "fastapi",
        "uvicorn",
        "sqlite3",
        "pydantic",
        "loguru",
        "requests",
        "schedule",
        "apscheduler",
        "apscheduler.triggers",
        "apscheduler.triggers.interval",
        "apscheduler.triggers.cron",
        "apscheduler.triggers.date",
        "apscheduler.executors",
        "apscheduler.executors.pool",
        "apscheduler.jobstores",
        "apscheduler.jobstores.memory",
        "scrcpy_client",
        "numpy",
        "PIL",
        "sklearn",
        "cv2",
        "psutil",
        # Project module imports (discovered by scanning)
        "config",
        "config.loader",
        "core",
        "core.adb",
        "core.device_manager",
        "core.phone",
        "core.mobile_ops",
        "scheduler",
        "scheduler.manager",
        "scheduler.priority",
        "scheduler.job_queue",
        "scheduler.runner",
        "monitor",
        "monitor.health",
        "monitor.phone_health",
        "monitor.api",
        "monitor.alerts",
        "monitor.poller",
        "monitor.reporter",
        "utils",
        "utils.logger",
        "utils.platform",
        "ai",
        "ai.utils",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tests",
        "tkinter",
        "matplotlib",
        "PIL.ImageShow",
        "PIL.ImageTk",
        "setuptools",
        "pip",
        "distutils",
        "curses",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="phone_farm_cli",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
