# scheduler package — job queue, cron logic, task runner, priority handling

from __future__ import annotations

from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class JobQueueProtocol(Protocol):
    """Interface for scheduler job queue implementations."""

    def enqueue(self, job_id: str, priority: int | str, payload: dict | None = None) -> dict: ...
    def dequeue(self) -> dict | None: ...
    def complete(self, job_id: str, result: Any = None) -> None: ...
    def fail(self, job_id: str, error: str | None = None) -> bool: ...
    def cancel(self, job_id: str) -> bool: ...
    def get_status(self, job_id: str) -> dict | None: ...
    def qsize(self) -> int: ...


@runtime_checkable
class TaskRunnerProtocol(Protocol):
    """Interface for task runner implementations."""

    def start(self, daemon: bool = True) -> None: ...
    def stop(self, timeout: float = 5.0) -> None: ...
    def run_once(self) -> dict | None: ...


__all__ = ["JobQueueProtocol", "TaskRunnerProtocol"]